---
video_input: 1              # Input Must be OpenCV readable 
visualize: True             # Disable for performance increase
vis_text: True              # Display fps on visualization stream
max_frames: 5000            # only used if visualize==False
execution_seconds: 60       # only used if visualize==False
width: 160                  # OpenCV only supports 4:3 formats others will be converted
height: 120                 # 600x600 leads to 640x480
fps_interval: 5             # Interval [s] to print fps of the last interval in console
det_interval: 100           # intervall [frames] to print detections to console
det_th: 0.5                 # detection threshold for det_intervall
split_model: True           # Splits Model into a GPU and CPU session (currently only works for ssd_mobilenets)
log_device: False           # Logs GPU / CPU device placement
allow_memory_growth: True   # limits memory allocation to the actual needs
image_path: 'test_images'   # used for image_detection.pyq
convert_rgb: True           # Converts BGR to RGB color (idk how it ever worked without this)
ssd_shape: 300              # used for the split model algorithm
                            # currently only supports ssd networks trained on 300x300 and 600x600 input
debug_mode: False           # Show FPS spike value

# Change only if you use another model
model_name: 'ssd_mobilenet_v1_coco'

# mscoco
#model_path: 'models/ssd_mobilenet_v11_coco/frozen_inference_graph.pb'
#label_path: 'object_detection/data/mscoco_label_map.pbtxt'
#num_classes: 90

# own data
model_path: 'models/ssd_mobilenet/roadsign_frozen_inference_graph_v1_2nd_4k.pb'
label_path: 'models/ssd_mobilenet/roadsign_label_map.pbtxt'
num_classes: 4
